# config/application.yml
defaults: &defaults
  host: localhost:3000
  admin_emails:
    - admin@teensdigest.com
    - duyn1337@gmail.com
  threshold: 0.8
  stat_threshold: 1.00
  pageview_threshold: 1.00
  under_threshold_chance: 0.8
  above_threshold_chance: 1.2

development:
  <<: *defaults
  random_query: RAND()
  isolated_cat_id: 3
  isolated_cat_name_cap: FITNESS
  isolated_cat_name: Fitness

test:
  <<: *defaults
  random_query: RANDOM()
  isolated_cat_id: 3
  isolated_cat_name_cap: FITNESS
  isolated_cat_name: Fitness

production:
  <<: *defaults
  random_query: RAND()
  isolated_cat_id: 10
  isolated_cat_name_cap: SPORTS
  isolated_cat_name: Sports
